### ISSUE TITLE
Demo Scene 3D Model

### ISSUE THREAD

**Issue by MarioCornell** [Strange-Land/Core#6]
Came across https://assetstore.unity.com/packages/3d/environments/urban/demo-city-by-versatile-studio-mobile-friendly-269772
It's a visually pleasing asset with decent lane setup.
Wrote to developers about permission and awaiting response. The only issue is that the ground texture looks a rained condition? Maybe I can ask for a normal texture if they allows the usage.

**Comment by DavidGoedicke** [comment]
I think that would be a great start and we should also look through UPM if we can find these kind of packages but that's a great start!
